#!/usr/bin/env python3
"""Fee tuning: how do the extra half-spread (hs) and the liquidity setting (b)
change the market maker's profit?

Runs the C++ market maker through the exchange over many seeded order streams
for every (b, hs) and writes docs/fee_tuning.md. Noise traders are
price-sensitive here (gen -elastic), otherwise a wider spread would always
look better.

    make && python3 tools/fee_sweep.py
"""
import pathlib
import re
import statistics
import subprocess

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "out" / "fee_sweep"

SEEDS = range(1, 21)
EVENTS = 4000
ELASTIC = 10                  # noise traders' limit is within 10 cents of the truth
LBS = (6, 7, 8)               # b = 64, 128, 256
HSS = (0, 1, 2, 3, 4, 6, 8)
INFORMED = (0.1, 0.3, 0.5)

def run(seed, informed, lb, hs):
    events = OUT / "sweep.events"
    subprocess.run([ROOT / "gen" / "gen", "-o", events, "-n", str(EVENTS), "-seed", str(seed),
                    "-p0", "0.35", "-news", f"{EVENTS // 2}:0.75", "-informed", str(informed),
                    "-elastic", str(ELASTIC), "-lb", str(lb), "-ls", "3", "-hs", str(hs)],
                   check=True, capture_output=True)
    out = subprocess.run([ROOT / "exchange" / "exchange", "--events", events, "--mm", "cmd:mm_cpp/mm_cpp"],
                         check=True, capture_output=True, text=True, cwd=ROOT).stdout
    fills = int(re.search(r"fills (\d+)", out).group(1))
    pnl = float(re.search(r"at true probability (-?[\d.]+)", out).group(1))
    return fills, pnl

def main():
    OUT.mkdir(parents=True, exist_ok=True)
    doc = ["# Fee tuning", "",
           "Generated by `tools/fee_sweep.py`. Each cell is the market maker's average profit in",
           f"dollars over {len(SEEDS)} seeded order streams of {EVENTS} trader arrivals (true probability 35%,",
           "jumping to 75% halfway), valued at the true probability at the end. In brackets: average",
           f"number of trades. Quote size 8. Noise traders walk away if the quote is more than their",
           f"private limit, which is within {ELASTIC} cents of the truth.", ""]
    csv = ["informed,b,hs,mean_pnl,stdev_pnl,mean_fills"]
    for informed in INFORMED:
        doc += [f"## {informed:.0%} informed traders", "",
                "| extra half-spread | " + " | ".join(f"b = {1 << lb}" for lb in LBS) + " |",
                "|---|" + "---|" * len(LBS)]
        best = None
        for hs in HSS:
            cells = []
            for lb in LBS:
                results = [run(seed, informed, lb, hs) for seed in SEEDS]
                pnl = statistics.mean(r[1] for r in results)
                fills = statistics.mean(r[0] for r in results)
                sd = statistics.stdev(r[1] for r in results)
                csv.append(f"{informed},{1 << lb},{hs},{pnl:.2f},{sd:.2f},{fills:.0f}")
                cells.append(f"{pnl:.0f} ({fills:.0f})")
                if best is None or pnl > best[0]:
                    best = (pnl, 1 << lb, hs)
            doc.append(f"| {hs}c | " + " | ".join(cells) + " |")
            print(f"informed {informed:.0%} hs {hs}: " + "  ".join(cells), flush=True)
        doc += ["", f"Best: b = {best[1]}, extra half-spread {best[2]}c, average profit ${best[0]:.0f}.", ""]
    (OUT / "fee_sweep.csv").write_text("\n".join(csv) + "\n")
    (ROOT / "docs" / "fee_tuning.md").write_text("\n".join(doc))
    print("wrote docs/fee_tuning.md and out/fee_sweep/fee_sweep.csv")

if __name__ == "__main__":
    main()
